### PR TITLE
Created PMT Hardware Trigger simulation producer

### PR DESCRIPTION
**Pull request by eyandel**
Definitions for the data product created by the pmtTriggerProducer module in SBNSoftware/sbndcode#214

### CODE REVIEW

**Comment by pgreen135** [comment]
@eyandel what is the purpose of `classes.h`? and same for the `pmtTrigger.cc` file, as this is empty

**Comment by eyandel** [comment]
> @eyandel what is the purpose of `classes.h`? and same for the `pmtTrigger.cc` file, as this is empty

These files are required for everything to compile properly, but this data product is currently very basic and doesn't yet need functions to go in here. So they should be mostly empty (with just some include statements) and do need to be here anyway.

**Comment by eyandel** [comment]
> @eyandel as per [SBNSoftware/sbndcode#214](https://github.com/SBNSoftware/sbndcode/pull/214) could you update this with some information? Are the two PRs required to go together? Is this required for the next production?

This is just the necessary definitions for the data product created by the pmtTriggerProducer module. I don't think it needs too much information and instructions since these scripts won't do anything without the module (which now has the more detailed information) and no one should really be changing these sbnobj files, they just need to exist to use the module or read it's outputs. So yes, the PR's should go together and both are needed for the module to work.

**Comment by pgreen135** [comment]
> > @eyandel what is the purpose of `classes.h`? and same for the `pmtTrigger.cc` file, as this is empty
> 
> These files are required for everything to compile properly, but this data product is currently very basic and doesn't yet need functions to go in here. So they should be mostly empty (with just some include statements) and do need to be here anyway.

Is the intent that these would be updated and added to in the future as this work develops further? If so I am happy with this.

**Comment by eyandel** [comment]
> > > @eyandel what is the purpose of `classes.h`? and same for the `pmtTrigger.cc` file, as this is empty
> > 
> > 
> > These files are required for everything to compile properly, but this data product is currently very basic and doesn't yet need functions to go in here. So they should be mostly empty (with just some include statements) and do need to be here anyway.
> 
> Is the intent that these would be updated and added to in the future as this work develops further? If so I am happy with this.

Yes definitely. This is just the first iteration.

**Review by pgreen135 — APPROVED** [review]

**Pull request merged**
