### PR TITLE
add wdith2 for pmNsigma mode

### PR DESCRIPTION
**Pull request by Ooohu**
Update on `sbnobj/Common/SBNEventWeight/EventWeightParameterSet.*` to match up the PR #176 at sbncode: https://github.com/SBNSoftware/sbncode/pull/176

### CODE REVIEW

**Review by mroda88 — COMMENTED** [review]
@Ooohu I'm sorry but this PR does not make any sense and we never discussed it before, so you need to explain a few things. 

What is the meaning of the second width? What is the usage case?
Your descriptions says
```
Gaussian sigma, if one more variation is needed
```
Which is not very descriptive. 
Also this does not provide a description of the changes for the fcl files.

**Comment by Ooohu** [comment]
> @Ooohu I'm sorry but this PR does not make any sense and we never discussed it before, so you need to explain a few things.
> 
> What is the meaning of the second width? What is the usage case? Your descriptions says
> 
> ```
> Gaussian sigma, if one more variation is needed
> ```
> 
> Which is not very descriptive. Also this does not provide a description of the changes for the fcl files.

Hello @mroda88, this description is for the lines 
https://github.com/SBNSoftware/sbnobj/blob/0ce442f288b08a99b52045bad04446367e7b7bc8/sbnobj/Common/SBNEventWeight/EventWeightParameterSet.cxx#L71:

```     
else if (fRWType == kPMNSigma) {
        it.second.push_back(p.fMean + p.fWidth);
        it.second.push_back(p.fMean + p.fWidth2);
      }
      ```
     
     I will update the description from
     ` float fWidth2;  //!< Gaussian sigma, if one more variation is needed` 
     to
     `  float fWidth2;  //!< for PMNSigma mode, which will requires two shifts to the knob: fmean+fWidth1 and fmean + fWidth2`.
     
When using PMNSigma mode, two universes (with two shifted values) are generated, and this is the reason why `fWidth2` is used.

**Comment by Ooohu** [comment]
Now only change the line at https://github.com/SBNSoftware/sbnobj/blob/337599381d1786c98aaf1e0d0734819a449643ce/sbnobj/Common/SBNEventWeight/EventWeightParameterSet.cxx#L64

**Review by mroda88 — APPROVED** [review]
great, thanks

**Pull request merged**
